### PR TITLE
Add holopin.yaml for website badge

### PR DESCRIPTION
**Pull request by rishabkumar7**
# Desciption
Add `holopin.yaml` config for the website badge.

# Issue
#92

### CODE REVIEW

**Review by marcduiker — APPROVED** [review]
LGTM

**Comment by marcduiker** [comment]
@holopin-bot @rishabkumar7

**Comment by rishabkumar7** [comment]
@marcduiker look like something is wrong with the config, do we have Holopin App installed for this repo?
Also, it might be the YAML too, here is the docs example:
``` yaml
organization: # org name on holopin
defaultSticker: # sticker ID
stickers:
  - id: # sticker id
    alias: # shorthand-string
  - id:
    alias:
  # more stickers
```

**Comment by marcduiker** [comment]
I think the YAML is fine, other repos use the same format. I need to look into the Holopin app configuration with one of the other maintainers.

**Comment by marcduiker** [comment]
@holopin-bot @rishabkumar7 another test!

**Comment by marcduiker** [comment]
It was the file extension 🙄. I'll file an issue at Holopin about this.

**Pull request merged**
